version: '3'

networks:
  smart_fridge:
    driver: bridge

services:
  flask_chatbot_python:
    image: hanktsai/pipenv_iii:3.7.2
    ports:
      - "5000:5000"
    environment:
      line_channel_access_token: <key>
      line_channel_secret: <key>
      TZ: 'Asia/Taipei' 
    volumes:
      - .:/work
    command: python nothing.py  # 純粹用來讓機器運作的無意義循環檔
    depends_on:
      - mysql
    networks:
      - smart_fridge


  ngrok:
    image: wernight/ngrok
    ports:
      - "4040:4040"
    environment:
      NGROK_AUTH: <your ngrok token>
      NGROK_PORT: flask_chatbot_python:5000
      NGROK_REGION: 'ap'
      TZ: 'Asia/Taipei' 
    depends_on:
      - flask_chatbot_python
    networks:
      - smart_fridge


  redis:
    image: bitnami/redis:latest
    container_name: redis
    hostname: redis
    restart: always
    ports:
      - 6379:6379
    depends_on:
      - mysql
    environment:
      - REDIS_PASSWORD=recipe
    volumes:
      - ./data/redis:/var/lib/redis
    networks:
      - smart_fridge


  mysql:
    image: mysql:latest
    container_name: mysql
    hostname: mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=<passwd>
    volumes:
      - ./data/mysql:/var/lib/mysql 
      - ./docker/data/mysql_init:/docker-entrypoint-initdb.d/
    networks:    
      - smart_fridge

  zookeeper:
    image: confluentinc/cp-zookeeper:5.2.1
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    depends_on:
      - flask_chatbot_python
    networks:
      - smart_fridge


  kafka:
    image: confluentinc/cp-kafka:5.2.1
    hostname: kafka
    container_name: kafka
    ports:
      - '9092:9092'
      - '29092:29092'
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      ## for local use
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      ## for public use
      #KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://<host_ip>:9092
      #advertised.host.name: <host_ip>
    networks:
      - smart_fridge
